### ISSUE TITLE
Critical notifications無法使用

### ISSUE THREAD

**Issue by hsianice** [kukuxx/HA-NotifyHelper#3]
configuration.yaml
已設定
notify:
  - name: mobile_app_user
    platform: group
    services:
      - service: mobile_app_user_iphone
-
整合Notify Helper已設定
Select Person: person.user
Select the devices you want to notify: mobile_app_user
-
action: notifyhelper.all
data:
  title: 地震速報
  message: >-
    預估 {{ states('sensor.earthquake_alert_level') }} 級地震，{{
    states('sensor.earthquake_alert_arrive_second') }} 秒後抵達。
  data:
    url: /lovelace/notification
    image: /local/image/eq_2024_11_24_01_19_22.png
    push:
      interruption-level: active
      sound:
        name: pwsos.wav
        volume: 0.3
        critical: 1

ios設備無法在靜音下發出自訂聲響通知，但action: notify.mobile_app_family可以發出聲響

**Comment by kukuxx** [comment]
@hsianice  請嘗試新版本問題我測試已修復，如果還有遇到其他問題可以先在整合裡開啟偵錯模式再把log和你的配置貼上來 &#x1F44D;

**Comment by hsianice** [comment]
測試後已經正常 感謝
