### ISSUE TITLE
jpg Image

### ISSUE THREAD

**Issue by Martin650523** [kukuxx/HA-NotifyHelper#4]
Is it possible to show the jpg image ?

And the png image can not show up.

**Comment by kukuxx** [comment]
Both JPG and PNG are available
Please confirm whether the automation parameters or image paths are correct
Check if there are any error logs

**Comment by Martin650523** [comment]
My image path is /config/media/Test.png and can not show. Is the path wrong ?

**Comment by kukuxx** [comment]
The default path of HA is /config/www. I don’t know if it can be used normally if placed in another path.
You can try to put in the default path and set it in automation:
image: /local/your.png
local will correspond to /config/www

**Comment by Martin650523** [comment]
> The default path of HA is /config/www. I don’t know if it can be used normally if placed in another path. You can try to put in the default path and set it in automation: image: /local/your.png local will correspond to /config/www

Thanks. It works and show in HA. But the markdown can not show the image, but only show the message.

**Comment by Martin650523** [comment]
> The default path of HA is /config/www. I don’t know if it can be used normally if placed in another path. You can try to put in the default path and set it in automation: image: /local/your.png local will correspond to /config/www

Thanks. It works and show from the paht /config/www in HA, and can not show in another path. Another problem is the markdown can not show the image, but only show the message.

**Comment by kukuxx** [comment]
Just reopen the browser. The problem has been solved, close the issue.
